### ISSUE TITLE
lsblk: invalid option

### ISSUE THREAD

**Issue by mx-lin** [jamielinux/bashmount#10]
An 'invalid option' error is issued:
mx@mx-lin ~/Downloads/bashmount-3.2.0 $ ./bashmount
lsblk: invalid option -- 'p'
Usage:
 lsblk [options] [<device> ...]
<snip>

One line looks suspicious:

mx@mx-lin ~/Downloads/bashmount-3.2.0 $ grep -n 'lsblk -p' bashmount
500:    all=( $(lsblk -plno NAME) )

The '-p ' option does not exist, according to 'man lsblk'.
Using here Ubuntu 14.04

**Comment by jamielinux** [comment]
Duplicate of issue #9. Your version of `lsblk` is too old. Ubuntu 14.10 and above have the version required.
