### ISSUE TITLE
ejecting not working without sudo password

### ISSUE THREAD

**Issue by gotbletu** [jamielinux/bashmount#14]
Command: 8e

    ==> Ejecting /dev/sdd2 ...

    eject: cannot open /dev/sdd: Permission denied

    Press [enter] to continue: 

Doesnt seem to eject device without sudo password. Mounting and unmount works fine though without any password requirements.

using: **udisk2**

**Comment by jamielinux** [comment]
This should be fixed now in bashmount v4.x, which runs `udisksctl power-off` instead of `eject`.

**Comment by gotbletu** [comment]
Thanks works good now

**Comment by jamielinux** [comment]
Brilliant! :+1: :rocket: 

P.S. Sorry for many years delay :see_no_evil:
