### ISSUE TITLE
Feature request: add option to format disks

### ISSUE THREAD

**Issue by LinArcX** [jamielinux/bashmount#19]
Hi. First thanks for your great effort. second i have a suggestion. It'll be very useful if we can format disks, like this:
`sudo mkfs.ntfs /dev/sdb1`

**Comment by jamielinux** [comment]
Cool idea and I agree it would be useful, but I think this might be out of scope for bashmount.

There's lots of cases to support to format disks (filesystems, labels, options, filesystem-specific options etc). I'm tempted to leave that to other tools.
