### ISSUE TITLE
does not properly exit after opening a device

### ISSUE THREAD

**Issue by AladW** [jamielinux/bashmount#8]
Command: 3o
==> Opening /dev/sdd1 ...
[alad@arbellen BACKUP USB] $ cd
[alad@arbellen ~]$ bashmount
Command: 3u
Error unmounting /dev/sdd1: GDBus.Error:org.freedesktop.UDisks2.Error.Failed: Error unmounting /dev/sdd1: Command-line `umount  "/media/BACKUP USB"' exited with non-zero exit status 32: umount: /media/BACKUP USB: target is busy

If you use "exit" to first terminate $SHELL bashmount launched, it works as intended. Not quite sure how to handle this, unless you opened a new terminal... something like 

cd "${1}" && (setsid "$SHELL"  &)

forks a new shell and exits bashmount, but the user doesn't see it.

**Comment by jamielinux** [comment]
As far as I'm aware, if there's a shell session open somewhere with working directory inside a mountpoint, you'll always have `target is busy` message. Best way is to close the shell, which is the approach I'm hoping most people are taking already.

P.S. Sorry for 6 year delay!
